package DerpSong;

import java.util.Arrays;

import DerpSong.items.items;
import DerpSong.network.packetHandler;
import DerpSong.proxies.ClientProxy;
import DerpSong.proxies.CommonProxy;
import DerpSong.util.config;
import DerpSong.util.resetCommand;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.event.FMLServerStartingEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid = ModInfo.MOD_ID, name = ModInfo.MOD_NAME, version = ModInfo.MOD_VERSION)
@NetworkMod(channels = {ModInfo.MOD_CHANNEL}, clientSideRequired = true, serverSideRequired = true, packetHandler = packetHandler.class)

public class Main {
	public static int hourTime;
	public static int configPlayTime;
	public static boolean isPlayingRecord;
	
	@Instance(ModInfo.MOD_ID)
	public static Main instance;
	
	@SidedProxy(clientSide = "DerpSong.proxies.ClientProxy", serverSide = "DerpSong.proxies.CommonProxy")
	public static CommonProxy proxy;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event){
	    config.createConfig(event.getSuggestedConfigurationFile());
		getModMeta(event.getModMetadata());
	    items.init();
	    ClientProxy.soundHandler();
		ClientProxy.tickHandler();
	}
	@EventHandler
	public void serverLoad(FMLServerStartingEvent event){
		event.registerServerCommand(new resetCommand());
	}
	
	@EventHandler
	public void load(FMLInitializationEvent event){
	}
	@EventHandler
	public void postLoad(FMLPostInitializationEvent event){
	}
	
	  private void getModMeta(ModMetadata meta)
	  {
	    meta.authorList = Arrays.asList(new String[] { "Mex" });
	    meta.logoFile = "null";
	    meta.autogenerated = false;
	    meta.credits = "Maintained by Mex";
	    meta.description = "This mod adds a derpy Record to Minecraft.";
	  }
}
